### ISSUE TITLE
In React -Reveal.destroy() → Error: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by brandontrew** [hakimel/reveal.js#3593]
Error: when trying to destroy() the reveal instance within React (per documentation)
```
Reveal.js destroy call failed. TypeError: Cannot read properties of undefined (reading 'forEach')
    at eval (reveal.esm.js:8:61023)
    at Array.forEach (<anonymous>)
    at M.unbind (reveal.esm.js:8:60987)
    at Se (reveal.esm.js:8:83644)
    at Object.destroy (reveal.esm.js:8:100765)
    at eval (RevealApp.jsx:95:31)
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitHookEffectListUnmount (react-dom.development.js:23100:1)
    at invokePassiveEffectUnmountInDEV (react-dom.development.js:25207:1)
    at invokeEffectsInDev (react-dom.development.js:27351:1)
```

Initialize & Return, per https://revealjs.com/react/
```
  useEffect(() => { 
      if (revealRef.current) return;
      let resizeObserver;

      revealRef.current = new Reveal(revealInitDivRef.current, RevealConfig);
      revealRef.current.initialize().then(() => {

        revealRef.current.addEventListener('drop', handleFileDrop);
        revealRef.current.on( 'slidechanged', event => {
          handleSlideChange(event)
        });
        revealRef.current.on('resize', event => {
          if (revealRef.current) {
            revealRef.current.sync();
            revealRef.current.layout();
          }
        });

        resizeObserver = new ResizeObserver(() => {
          if (revealRef.current) {
            revealRef.current.sync();
            revealRef.current.layout();
          }
        });
        if (revealElement) resizeObserver.observe(revealElement);

        revealRef.current.sync();
        revealRef.current.layout();
        setRevealInitialized(true);

      })
      .catch(error => {
        console.error("Failed to initialize editor:", error);
      });

      return () => {
        try {
          if (revealRef.current) {
            console.log('revealRef.current',revealRef.current);
            revealRef.current.destroy();
            revealRef.current = null;
          }
        } catch (e) {
          console.warn("Reveal.js destroy call failed.", e);
        }
      };

    }, []);
```

**Comment by hakimel** [comment]
This was happening when calling the `destroy` method for a reveal.js instance that hadn't been initialized. Fixed in 0799c8f67497c1c55cc3e711e19d20c2ff3eb8b8

**Comment by hakimel** [comment]
Sidenote, in your example you shouldn't need to call `revealRef.current.layout()`. Your call to `revealRef.current.sync()` already triggers a layout so it's being called twice.

**Comment by brandontrew** [comment]
Many thanks. I'm rendering new async slides into reveal, and they were all
showing up stacked on top of each other - I was trying sync/layout and
anything else. What worked is setting a specific move to slide().

**Comment by SoheilSalmani** [comment]
I still get the warning log using the example from the docs, even in 5.1.0. But, using the `isReady` method removes the warning.

```jsx
return () => {
  try {
    if (revealRef?.current?.isReady()) {
      revealRef.current.destroy();
      revealRef.current = null;
    }
  } catch (e) {
    console.warn("Reveal.js destroy call failed.");
  }
};
```

**Comment by hakimel** [comment]
Thanks @SoheilSalmani. I've revised this again;
- Destroy now internally only proceeds with destruction if the presentation is ready.
- If a presentation is destroyed mid-initialization it will no longer fire a 'ready' event after async assets finish loaded.
- Added tests.
